version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    # environment:
    #   DB_HOST: your-rds-endpoint.amazonaws.com
    #   DB_USER: admin
    #   DB_PASSWORD: password
    #   DB_NAME: formdb