pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = 412664885824

        FRONTEND_REPO = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend-ecr-repo"
        BACKEND_REPO  = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend-ecr-repo"
    }

    stages {

        stage('Checkout Source') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/BhushanBagde123/form-project.git'
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('frontend') {
                    sh 'docker build -t frontend:v1 .'
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t backend:v1 .'
                }
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }

        stage('Tag Images') {
            steps {
                sh '''
                docker tag frontend:v1 ${FRONTEND_REPO}:v1
                docker tag backend:v1 ${BACKEND_REPO}:v1
                '''
            }
        }

        stage('Push Images to ECR') {
            steps {
                sh '''
                docker push ${FRONTEND_REPO}:v1
                docker push ${BACKEND_REPO}:v1
                '''
            }
        }
        stage('Deployment') {
            steps {
                sh 'chmod +x scripts/deploy.sh'
                sh './scripts/deploy.sh'
    }
}
    }

    post {
        success {
            echo "Deployment successfull."
        }

        failure {
            echo "Pipeline failed."
        }
    }
    
}